
import { Lesson } from './types';

export const LESSONS: Lesson[] = [
  {
    id: 1,
    title: '第一課：韻母大集合',
    subtitle: 'i / u 行韻母辨識與組合',
    icon: '🏠',
    animal: '🐰',
    questions: [
      { id: 101, category: 'i 行韻母', question: '1. 「衣」的韻母是？', options: ['i', 'ia', 'ie'], correctIndex: 0, explanation: '「衣」是單韻母 i。' },
      { id: 102, category: 'i 行韻母', question: '2. 「鴉」(ya) 的韻母是？', options: ['i', 'ia', 'iao'], correctIndex: 1, explanation: '「鴉」的韻母是 ia。' },
      { id: 103, category: 'i 行韻母', question: '3. 「耶」(ye) 的韻母是？', options: ['ie', 'iao', 'iou'], correctIndex: 0, explanation: '「耶」的韻母是 ie。' },
      { id: 104, category: 'i 行韻母', question: '4. 「腰」(yao) 的韻母是？', options: ['iao', 'ian', 'in'], correctIndex: 0, explanation: '「腰」的韻母是 iao。' },
      { id: 105, category: 'i 行韻母', question: '5. 「優」(you) 的實際韻母組合是？', options: ['iou', 'iu', 'u'], correctIndex: 0, explanation: '實際是 iou，拼寫縮寫為 iu。' },
      { id: 106, category: 'i 行韻母', question: '6. 「煙」(yan) 的韻母是？', options: ['ian', 'in', 'iang'], correctIndex: 0, explanation: '「煙」的韻母是 ian。' },
      { id: 107, category: 'i 行韻母', question: '7. 「音」(yin) 的韻母是？', options: ['in', 'ing', 'ian'], correctIndex: 0, explanation: '「音」的韻母是 in。' },
      { id: 108, category: 'i 行韻母', question: '8. 「亮」(liang) 的韻母是？', options: ['iang', 'ang', 'ing'], correctIndex: 0, explanation: '「亮」的韻母是 iang。' },
      { id: 109, category: 'i 行韻母', question: '9. 「影」(ying) 的韻母是？', options: ['ing', 'in', 'iang'], correctIndex: 0, explanation: '「影」的韻母是 ing。' },
      { id: 110, category: 'i 行韻母', question: '10. 「兄」(xiong) 的韻母是？', options: ['iong', 'ong', 'iang'], correctIndex: 0, explanation: '「兄」的韻母是 iong。' },
      { id: 111, category: 'u 行韻母', question: '11. 「烏」(wu) 的韻母是？', options: ['u', 'ua', 'uo'], correctIndex: 0, explanation: '「烏」是單韻母 u。' },
      { id: 112, category: 'u 行韻母', question: '12. 「蛙」(wa) 的韻母是？', options: ['ua', 'uai', 'uei'], correctIndex: 0, explanation: '「蛙」的韻母是 ua。' },
      { id: 113, category: 'u 行韻母', question: '13. 「窩」(wo) 的韻母是？', options: ['uo', 'uan', 'uen'], correctIndex: 0, explanation: '「窩」的韻母是 uo。' },
      { id: 114, category: 'u 行韻母', question: '14. 「外」(wai) 的韻母組合是？', options: ['ua', 'uai', 'uei'], correctIndex: 1, explanation: '「外」的韻母是 uai。' },
      { id: 115, category: 'u 行韻母', question: '15. 「堆」(dui) 的實際韻母組合是？', options: ['ui', 'uei', 'uei'], correctIndex: 1, explanation: '實際是 uei，拼寫縮寫為 ui。' },
      { id: 116, category: 'u 行韻母', question: '16. 「萬」(wan) 的韻母是？', options: ['uan', 'un', 'uang'], correctIndex: 0, explanation: '「萬」的韻母是 uan。' },
      { id: 117, category: 'u 行韻母', question: '17. 「問」(wen) 的實際韻母組合是？', options: ['uen', 'un', 'un'], correctIndex: 0, explanation: '實際是 uen，拼寫縮寫為 un。' },
      { id: 118, category: 'u 行韻母', question: '18. 「黃」(huang) 的韻母是？', options: ['uang', 'ueng', 'ang'], correctIndex: 0, explanation: '「黃」的韻母是 uang。' },
      { id: 119, category: 'u 行韻母', question: '19. 「翁」(weng) 的韻母是？', options: ['ueng', 'ong', 'uong'], correctIndex: 0, explanation: '「翁」的韻母是 ueng。' },
      { id: 120, category: '綜合練習', question: '20. 「游泳」(you yong) 中「游」的韻母是？', options: ['iou', 'u', 'iu'], correctIndex: 0, explanation: '「游」的韻母原形是 iou。' }
    ]
  },
  {
    id: 2,
    title: '第二課：ü 的小秘密',
    subtitle: 'ü 行規則與 j / q / x 組合',
    icon: '🤝',
    animal: '🐶',
    questions: [
      { id: 201, category: 'ü 行辨析', question: '1. 「學」(xue) 的韻母原形是？', options: ['üe', 'ue', 'ie'], correctIndex: 0, explanation: '「學」的原形是 üe。' },
      { id: 202, category: 'ü 行辨析', question: '2. 「全」(quan) 的韻母原形是？', options: ['uan', 'üan', 'an'], correctIndex: 1, explanation: '「全」的原形是 üan。' },
      { id: 203, category: 'ü 行辨析', question: '3. 「均」(jun) 的韻母原形是？', options: ['un', 'ün', 'in'], correctIndex: 1, explanation: '「均」的原形是 ün。' },
      { id: 204, category: '拼寫規則', question: '4. j, q, x 見到 ü 時，兩點要？', options: ['保留', '去掉', '變成一橫'], correctIndex: 1, explanation: '小 ü 見到 j q x，兩點抹去還唸 ü。' },
      { id: 205, category: 'ü 行辨析', question: '5. 「趣」(qu) 的韻母是？', options: ['u', 'ü', 'i'], correctIndex: 1, explanation: '「趣」的韻母是 ü。' },
      { id: 206, category: '自成音節', question: '6. 韻母 üe 自成音節時，應寫作？', options: ['üe', 'yüe', 'yue'], correctIndex: 2, explanation: '加 y 去兩點寫作 yue。' },
      { id: 207, category: '自成音節', question: '7. 韻母 üan 自成音節時，應寫作？', options: ['yuan', 'üan', 'yüan'], correctIndex: 0, explanation: '加 y 去兩點寫作 yuan。' },
      { id: 208, category: '自成音節', question: '8. 韻母 ün 自成音節時，應寫作？', options: ['yun', 'ün', 'yün'], correctIndex: 0, explanation: '加 y 去兩點寫作 yun。' },
      { id: 209, category: '對比練習', question: '9. 「n」和「ü」相拼時，兩點要？', options: ['去掉', '保留', '不需要'], correctIndex: 1, explanation: 'n, l 見到 ü，兩點不能去！' },
      { id: 210, category: '對比練習', question: '10. 「l」和「ü」相拼時，音節是？', options: ['lü', 'lu', 'lyu'], correctIndex: 0, explanation: 'l 見到 ü，兩點必須留著。' },
      { id: 211, category: '拼寫辨析', question: '11. 「橘子」的「橘」正確拼寫是？', options: ['jú', 'jǘ', 'jiú'], correctIndex: 0, explanation: 'j 與 ü 拼，去掉兩點。' },
      { id: 212, category: '拼寫辨析', question: '12. 「宣傳」的「宣」正確拼寫是？', options: ['xuān', 'xüān', 'xiuān'], correctIndex: 0, explanation: 'x 與 üan 拼，去點寫作 xuan。' },
      { id: 213, category: '自成音節', question: '13. 「雨」自成音節的正確寫法是？', options: ['yǔ', 'ǚ', 'yǚ'], correctIndex: 0, explanation: '加 y 去點寫作 yǔ。' },
      { id: 214, category: '自成音節', question: '14. 「雲」自成音節的正確寫法是？', options: ['yún', 'ǘn', 'yǘn'], correctIndex: 0, explanation: '加 y 去點寫作 yún。' },
      { id: 215, category: '規則考驗', question: '15. 下列哪一組聲母拼 ü 時不去掉兩點？', options: ['j q x', 'n l', 'y'], correctIndex: 1, explanation: '只有 n, l 相拼時要保留兩點。' },
      { id: 216, category: '拼寫辨析', question: '16. 「虐待」的「虐」正確拼寫是？', options: ['nüè', 'nuè', 'niè'], correctIndex: 0, explanation: 'n 與 üe 拼，兩點必須留著。' },
      { id: 217, category: '拼寫辨析', question: '17. 「略過」的「略」正確拼寫是？', options: ['lüè', 'luè', 'liè'], correctIndex: 0, explanation: 'l 與 üe 拼，兩點必須留著。' },
      { id: 218, category: '拼寫辨析', question: '18. 「許可」的「許」正確拼寫是？', options: ['xǔ', 'xǚ', 'xiǔ'], correctIndex: 0, explanation: 'x 與 ü 拼，兩點去掉。' },
      { id: 219, category: '拼寫辨析', question: '19. 「軍隊」的「軍」正確拼寫是？', options: ['jūn', 'jǘn', 'jiūn'], correctIndex: 0, explanation: 'j 與 ün 拼，兩點去掉。' },
      { id: 220, category: '綜合練習', question: '20. 「圓圈」中「圓」的正確音節是？', options: ['yuán', 'üán', 'yüán'], correctIndex: 0, explanation: '加 y 去兩點寫作 yuán。' }
    ]
  },
  {
    id: 3,
    title: '第三課：標調小能手',
    subtitle: '標調順序與 i / u 並列規則',
    icon: '📞',
    animal: '🦒',
    questions: [
      { id: 301, category: '優先級', question: '1. 拼音標調的第一優先字母是？', options: ['o', 'e', 'a'], correctIndex: 2, explanation: '口訣：有 a 不放過，a 是標調的老大。' },
      { id: 302, category: '優先級', question: '2. 如果音節中沒有 a，接著找？', options: ['o, e', 'i, u', 'ü'], correctIndex: 0, explanation: '口訣：沒 a 找 o、e。' },
      { id: 303, category: '並列規則', question: '3. 在音節 xiu 中，聲調應該標在？', options: ['標在 i 上', '標在 u 上', '隨便選一個'], correctIndex: 1, explanation: '口訣：i、u 並列標在後。這裡 u 在後。' },
      { id: 304, category: '並列規則', question: '4. 在音節 dui 中，聲調應該標在？', options: ['標在 u 上', '標在 i 上', '標在 d 上'], correctIndex: 1, explanation: '口訣：i、u 並列標在後。這裡 i 在後。' },
      { id: 305, category: '標調位置', question: '5. 在音節 qiu 中，聲調應該標在？', options: ['標在 q 上', '標在 i 上', '標在 u 上'], correctIndex: 2, explanation: 'i、u 並列標在後。' },
      { id: 306, category: '標調位置', question: '6. 在音節 gui 中，聲調應該標在？', options: ['標在 g 上', '標在 u 上', '標在 i 上'], correctIndex: 2, explanation: 'i、u 並列標在後。' },
      { id: 307, category: '優先級', question: '7. 在音節 gei 中，聲調應該標在？', options: ['標在 i 上', '標在 e 上', '標在 g 上'], correctIndex: 1, explanation: '沒 a 找 o、e。這裡有 e 標在 e 上。' },
      { id: 308, category: '優先級', question: '8. 在音節 cao 中，聲調應該標在？', options: ['標在 c 上', '標在 a 上', '標在 o 上'], correctIndex: 1, explanation: '有 a 不放過！' },
      { id: 309, category: '優先級', question: '9. 在音節 gou 中，聲調應該標在？', options: ['標在 g 上', '標在 o 上', '標在 u 上'], correctIndex: 1, explanation: '沒 a 找 o。' },
      { id: 310, category: '並列規則', question: '10. 音節 liu 標第三聲時，正確寫法是？', options: ['lǐu', 'liǔ', 'liù'], correctIndex: 1, explanation: '標在後面那個字母 u 上。' },
      { id: 311, category: '並列規則', question: '11. 音節 shui 標第三聲時，正確寫法是？', options: ['shuǐ', 'shǔi', 'shui'], correctIndex: 0, explanation: '標在後面那個字母 i 上。' },
      { id: 312, category: '標調細節', question: '12. 標 i 的聲調時，i 原本的小點要？', options: ['保留', '去掉', '變成大點'], correctIndex: 1, explanation: '標調時，i 上的小點要抹去。' },
      { id: 313, category: '優先級', question: '13. 在音節 yue 中，聲調應該標在？', options: ['標在 y 上', '標在 u 上', '標在 e 上'], correctIndex: 2, explanation: '沒 a 找 o、e。這裡有 e。' },
      { id: 314, category: '標調順序', question: '14. 「有 a 找 a，沒 a 找 o e」這句口訣對嗎？', options: ['對', '不對', '不知道'], correctIndex: 0, explanation: '這是標準的標調順序。' },
      { id: 315, category: '優先級', question: '15. 在音節 niao 中，聲調應該標在？', options: ['標在 i 上', '標在 a 上', '標在 o 上'], correctIndex: 1, explanation: '有 a 不放過。' },
      { id: 316, category: '優先級', question: '16. 在音節 xue 中，聲調應該標在？', options: ['標在 u 上', '標在 e 上', '標在 x 上'], correctIndex: 1, explanation: '有 e 標在 e 上。' },
      { id: 317, category: '並列規則', question: '17. 音節 kui 標第二聲時，正確寫法是？', options: ['kúi', 'kuí', 'kuì'], correctIndex: 1, explanation: 'i、u 並列標在後，標在 i 上。' },
      { id: 318, category: '優先級', question: '18. 在音節 kao 中，聲調應該標在？', options: ['標在 k 上', '標在 a 上', '標在 o 上'], correctIndex: 1, explanation: '有 a 標在 a 上。' },
      { id: 319, category: '優先級', question: '19. 在音節 fei 中，聲調應該標在？', options: ['標在 f 上', '標在 e 上', '標在 i 上'], correctIndex: 1, explanation: '沒 a 找 o、e。' },
      { id: 320, category: '並列規則', question: '20. 音節 jiu 標第三聲時，正確寫法是？', options: ['jiǔ', 'jǐu', 'jiù'], correctIndex: 0, explanation: 'i、u 並列標在後，標在 u 上。' }
    ]
  },
  {
    id: 6,
    title: '綜合大冒險',
    subtitle: '拼音小達人：20 題全能挑戰！',
    icon: '🌈',
    animal: '🦁',
    questions: [
      { id: 601, category: '混合', question: '1. 「優」(you) 的實際韻母是？', options: ['iou', 'iu', 'u'], correctIndex: 0, explanation: '實際為 iou。' },
      { id: 602, category: '混合', question: '2. 當 q 與 üan 拼時，音節寫作？', options: ['qüan', 'quán', 'qian'], correctIndex: 1, explanation: '去掉兩點。' },
      { id: 603, category: '混合', question: '3. 音節 qiu 標聲調在？', options: ['i', 'u', 'q'], correctIndex: 1, explanation: '並列標在後。' },
      { id: 604, category: '混合', question: '4. 「鴉」(ya) 的韻母是？', options: ['ia', 'a', 'ua'], correctIndex: 0, explanation: 'ia。' },
      { id: 605, category: '混合', question: '5. 「烏」自成音節正確寫法？', options: ['u', 'wu', 'wū'], correctIndex: 2, explanation: '加 w。' },
      { id: 606, category: '混合', question: '6. 標調順序第一位？', options: ['o', 'e', 'a'], correctIndex: 2, explanation: 'a 是第一位。' },
      { id: 607, category: '混合', question: '7. 「全」(quan) 的原韻母是？', options: ['uan', 'üan', 'an'], correctIndex: 1, explanation: 'üan。' },
      { id: 608, category: '混合', question: '8. 「xue」的原韻母是？', options: ['x+üe', 'x+ue', 'x+ie'], correctIndex: 0, explanation: 'üe。' },
      { id: 609, category: '混合', question: '9. 音節 hui 標聲調在？', options: ['u', 'i', 'h'], correctIndex: 1, explanation: '並列標在後。' },
      { id: 610, category: '混合', question: '10. 「音」(yin) 的韻母是？', options: ['in', 'ing', 'ian'], correctIndex: 0, explanation: 'in。' },
      { id: 611, category: '混合', question: '11. 「旁邊」的「邊」(bian) 韻母是？', options: ['an', 'ian', 'uan'], correctIndex: 1, explanation: 'ian。' },
      { id: 612, category: '混合', question: '12. 「n」拼「ü」需要去點嗎？', options: ['需要', '不需要', '隨便'], correctIndex: 1, explanation: '不需要。' },
      { id: 613, category: '混合', question: '13. 音節 jue 標聲調在？', options: ['u', 'e', 'j'], correctIndex: 1, explanation: '標 e。' },
      { id: 614, category: '混合', question: '14. 「藥丸」正確音節拼寫？', options: ['yao wan', 'iao uan', 'yao uan'], correctIndex: 0, explanation: 'y/w 變換。' },
      { id: 615, category: '混合', question: '15. 「耶」(ye) 的韻母是？', options: ['ie', 'ia', 'ue'], correctIndex: 0, explanation: 'ie。' },
      { id: 616, category: '混合', question: '16. 音節 jiu 標聲調在？', options: ['i', 'u', 'j'], correctIndex: 1, explanation: '並列標在後。' },
      { id: 617, category: '混合', question: '17. 標調時 i 的小點應？', options: ['保留', '去掉', '變大'], correctIndex: 1, explanation: '去掉。' },
      { id: 618, category: '混合', question: '18. 「外」(wai) 的韻母是？', options: ['ua', 'uai', 'uei'], correctIndex: 1, explanation: 'uai。' },
      { id: 619, category: '混合', question: '19. 「問」(wen) 的實際韻母組合？', options: ['uen', 'un', 'un'], correctIndex: 0, explanation: 'uen。' },
      { id: 620, category: '混合', question: '20. 下列正確標調的是？', options: ['qíu', 'xiū', 'dùi'], correctIndex: 1, explanation: 'xiū 正確（標在後）。' }
    ]
  }
];
